author: manf
database: false
description: TODO
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: de.javakara.manf.mcbb.MCbb
name: MCbb
startup: postworld
url: http://exo-network.de/
version: '1.8.0.0'
softdepend: [Vault]
commands:
   mcbb:
      description: This is a demo command.
permissions:
    mcbb.*:
        default: op
        description: Gives access to all commands
        children:
            mcbb.maintainer.*: true
            mcbb.vip.*: true
            mcbb.user.*: true
    mcbb.maintainer.*:
        default: op
        description: Allows all maintaining commands
        children:
            mcbb.maintainer.on: true
            mcbb.maintainer.off: true
            mcbb.maintainer.status: true
            mcbb.maintainer.update: true
    mcbb.vip.*:
        default: op
        description: Allows all vip commands
        children:
            mcbb.vip.override: true
    mcbb.user.*:
        default: true
        description: Allows all user commands
        children:
            mcbb.user.lookup: true
            mcbb.user.join: true

    mcbb.maintainer.on:
        description: Allows changing the Plugin Status to on
        default: op
    mcbb.maintainer.off:
        description: Allows changing the Plugin Status to off
        default: op
    mcbb.maintainer.status:
        description: Displays Status
        default: op
    mcbb.maintainer.update:
        description: Player is informed about Updates
        default: op
        
    mcbb.vip.override:
        description: Player does not need a Forum Account.
        default: op

    mcbb.user.lookup:
        description: Display whether player has Forum Account or not 
        default: true
    mcbb.user.join:
        description: Can join Server, otherwise will get kicked!
        default: true